# Generated by Django 5.2.4 on 2025-09-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this course without deleting it.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('basic', 'Basic Maintenance'), ('advanced', 'Advanced Repairs'), ('electric', 'Electric Bikes'), ('safety', 'Safety & Health'), ('history', 'History')], max_length=50),
        ),
    ]
